name:                three-layer
version:             0.1.0.0
github:              "githubuser/three-layer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md
- proto/foo.proto

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-protoc

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/three-layer#readme>

dependencies:
- base >= 4.7 && < 5
- protolude >= 0.1 && < 0.2
- mtl
- postgresql-simple
- resource-pool
- containers
- bcrypt
- servant
- servant-server
- jwt
- random
- uuid-types
- aeson
- time
- warp
- monad-logger
- ekg
- ekg-core
- data-default
- microlens
- proto-lens
- lens-labels
- proto-lens-protoc
- servant-proto-lens

default-extensions:
- OverloadedStrings
- NoImplicitPrelude
- GeneralizedNewtypeDeriving
- RecordWildCards
- FlexibleContexts
- RecordWildCards

library:
  source-dirs: src
  other-modules:
    - Proto.Foo

executables:
  three-layer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - three-layer
    other-modules:
      - Proto.Foo

tests:
  three-layer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - three-layer
    - tasty
    - tasty-discover
    - tasty-quickcheck
    - tasty-hspec
